CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(40) UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "folders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "name" varchar(256) NOT NULL,
  "parent_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "deleted_by" int
);

CREATE TABLE "files" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "folder_id" int,
  "name" varchar(256) NOT NULL,
  "extension" varchar(20),
  "size" bigint,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "deleted_by" int
);

CREATE INDEX ON "folders" ("user_id");

CREATE INDEX ON "folders" ("parent_id");

CREATE INDEX ON "files" ("user_id");

CREATE INDEX ON "files" ("folder_id");

CREATE INDEX ON "files" ("status");

ALTER TABLE "files" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "files" ADD FOREIGN KEY ("folder_id") REFERENCES "folders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "folders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "folders" ADD FOREIGN KEY ("parent_id") REFERENCES "folders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "files" ADD FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "folders" ADD FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
